# Generated by Django 4.0.6 on 2022-08-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidaturas',
            name='pontos',
            field=models.IntegerField(default=0),
        ),
    ]
