# Generated by Django 4.0.6 on 2022-08-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0002_alter_vagas_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagas',
            name='candidatura',
            field=models.IntegerField(default=1),
        ),
    ]
