# Generated by Django 4.0.6 on 2022-08-10 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0002_candidaturas_pontos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidaturas',
            name='pontos',
        ),
    ]
