# Generated by Django 4.0.6 on 2022-08-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='candidatura',
            field=models.IntegerField(default=1),
        ),
    ]
