# Generated by Django 4.0.6 on 2022-08-10 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='pontos',
        ),
    ]
