# Generated by Django 4.0.6 on 2022-08-07 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_candidato_candidatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='candidatura',
        ),
    ]
